version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - server
      - client
    volumes:
      - type: bind
        source: ./server/database.sqlite
        target: /app/database.sqlite
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - client

networks:
  server:
  client:
