version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - server
      - client
    ports:
      - '3001:3001'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - client

networks:
  server:
  client:
